/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn upfirdn2d_ffi(
        x: *const ::std::os::raw::c_void,
        f: *const ::std::os::raw::c_void,
        upx: ::std::os::raw::c_int,
        upy: ::std::os::raw::c_int,
        downx: ::std::os::raw::c_int,
        downy: ::std::os::raw::c_int,
        padx0: ::std::os::raw::c_int,
        padx1: ::std::os::raw::c_int,
        pady0: ::std::os::raw::c_int,
        pady1: ::std::os::raw::c_int,
        flip: bool,
        gain: f32,
    ) -> *mut ::std::os::raw::c_void;
}
